const Data =[
    {
        id:'1',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYdDaGFJQtl7L6BBY0NobQqPwr4fi3OsL-Kw&usqp=CAU",
        duration: '3 hrs',
        date: "20.01.2001",
        heading: "JavaScript Mastery Course for biggeners",
        desc: "A complete JavaScript reference, including all HTML and browser objects. The reference contains examples for all properties, methods and JavaScript Introduction.",
        price:"\u20B9.499/-",
    },
    {
        id: '2',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ7fRI35uj0Mwu-5fevWhsJe7oPyeFwXuofg&usqp=CAU",
        duration: '5 hrs',
        date: "30.01.2010",
        heading: "Figma Mastery Course for biggeners",
        desc: "Figma is the leading collaborative design tool for building meaningful products. Seamlessly design, prototype, develop, and collect feedback in a single ...",
        price:"\u20B9.699/-",
    },
    {
        id: '3',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_mWNPiC0HrzS55bHXcFBqF3Cp4nkoZA4vNw&usqp=CAU",
        duration: '2 hrs',
        date: "01.07.2012",
        heading: "HTML Mastery Course for biggeners",
        desc: "HTML is the standard markup language for Web pages. With HTML you can create your own Website. HTML is easy to lea",
        price:"\u20B9.800/-",
    },
    {
        id: '4',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkEjeu35noJ3ZtAf9ziLXsbjaMQYNxufrEaw&usqp=CAU",
        duration: '8 hrs',
        date: "15.05.2020",
        heading: "CSS Mastery Course for biggeners",
        desc: "CSS is the language we use to style an HTML document. CSS describes how HTML elements should be displayed. This tutorial will teach you CSS from . ",
        price:"\u20B9.1020/-",
    },
    {
        id: '5',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWela1xfcgWvCeS-_-Fkub6dfZzgYxG9-I4g&usqp=CAU",
        duration: '6 hrs',
        date: "25.02.2021",
        heading: "Java Mastery Course for biggeners",
        desc: "Java is a popular programming language. Java is used to develop mobile apps, web apps, desktop apps, games and much more.",
        price:"\u20B9.1200/-",
    },
    {
        id: '6',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0u45QFLB7kK_AAPvAmkH1cCHykaZM2XihSw&usqp=CAU",
        duration: '3 hrs',
        date: "28.09.2022",
        heading: "Script Mastery Course for biggeners",
        desc: "The <script> HTML element is used to embed executable code or data; this is typically used to embed or refer to JavaScript code.",
        price:"\u20B9.900/-",
    },
    {
        id: '7',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq4J8DF_tXiuCPwnSofwKCuWEKa7J1CshwmwEjE9o-EKJQUix5rV1CK_LHOndS9-cdekc&usqp=CAU",
        duration: '9 hrs',
        date: "28.02.2020",
        heading: "Mangodb Mastery Course for biggeners",
        desc: "Get your ideas to market faster with a developer data platform built on the leading modern database. MongoDB makes working with data easy.",
        price:"\u20B9.1399/-",
    },
    {
        id: '8',
        src :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA214QbKtunBlrHG-yY7uzIhpD4GtsfI1n1A&usqp=CAU",
        duration: '10 hrs',
        date: "28.10.2019",
        heading: "Express js Mastery Course for biggeners",
        desc: "Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications. APIs.",
        price:"\u20B9.1500/-",
    },
]
export default Data;